import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import MainTheme from "./theme/theme";
import { ContextProvider } from "./context/mainContext";
const quickSand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.JSX.Element;
}>) {
  return (
    <html lang="en">
      <body className={quickSand.className}>
        <MainTheme>
          <ContextProvider>
            {children}
          </ContextProvider>
        </MainTheme>
      </body>
    </html>
  );
}
