const ENFJdata = `
ENFJs are charismatic, passionate, and natural-born leaders who excel at connecting with others. They often find themselves in positions of influence, such as politicians, coaches, and teachers. Their genuine interest in others and strong sense of responsibility make them effective at guiding teams toward common goals. ENFJs have a talent for seeing the potential in people and are highly insightful about their motivations and feelings. However, their focus on others can lead to overcommitting and neglecting their own needs. Balancing personal well-being with their desire to help can be a challenge for ENFJs. They are warm, empathetic, and persuasive communicators, driven by a deep-seated need to make a positive impact. ENFJs thrive in collaborative environments and excel at fostering harmony and cooperation. They are often idealistic and have high standards for themselves and others, striving for continuous improvement. While they can be perfectionists, their dedication and ability to inspire make them powerful forces for good. ENFJs are adept at navigating social dynamics and are often seen as the glue that holds groups together. They are future-oriented, always looking for ways to improve the world around them. This can sometimes lead to frustration when their ideals clash with reality. Nevertheless, their optimism and determination enable them to overcome obstacles and achieve their goals. In relationships, ENFJs are supportive and nurturing, often going out of their way to ensure their loved ones feel valued and appreciated. They seek deep, meaningful connections and are willing to invest considerable time and energy into maintaining them. Ultimately, ENFJs are driven by a desire to leave a lasting, positive legacy, making a difference in the lives of those they encounter.
`;

const INFJdata = `
INFJs are deeply insightful, creative, and driven by strong personal values. They often feel a profound sense of purpose and are committed to making a positive impact on the world. Known for their ability to understand complex issues and see patterns others might miss, INFJs possess a unique blend of intuition and analytical skills. They are empathetic and connect with others on a deep level, valuing authenticity and striving to live in alignment with their principles. While they can be idealistic, they also face challenges when reality doesn't meet their high expectations. This can lead to frustration and a sense of disillusionment. INFJs are perfectionists, often holding themselves to incredibly high standards, which can result in self-criticism. Despite these challenges, their dedication to their ideals and ability to inspire others make them powerful advocates for change. INFJs excel in roles where they can help others and pursue their vision of a better world. They are often found in careers such as counseling, teaching, writing, and social activism. Their strong sense of empathy and desire for harmony can sometimes lead to taking on too much responsibility for others' emotions, making self-care essential. In relationships, INFJs seek deep, meaningful connections and are highly attuned to their partners' needs and feelings. They are supportive, nurturing, and willing to invest significant effort into maintaining healthy, fulfilling relationships. However, they may struggle with expressing their own needs and setting boundaries. Overall, INFJs are guided by their inner values and vision for a better future. Their ability to inspire and connect with others, combined with their determination and creativity, makes them influential and transformative individuals. They leave a lasting impact on those they encounter, driven by their unwavering commitment to making a difference.
`;

const ENFPdata = `
ENFPs are enthusiastic, creative, and sociable individuals who bring energy and excitement to any situation. They are often seen as the life of the party, known for their upbeat outlook and ability to inspire others. ENFPs are highly imaginative, always exploring new ideas and possibilities. They value individuality and authenticity, seeking to express themselves and encourage others to do the same. Their strong people-oriented nature makes them excellent at building relationships and fostering a sense of community. However, their enthusiasm for new experiences can sometimes lead to difficulty in staying focused and following through on projects. ENFPs are highly empathetic, often taking on the emotions of those around them, which can be both a strength and a challenge. Their sensitivity to others' feelings allows them to connect deeply but also means they need to be mindful of their own emotional well-being. In their careers, ENFPs thrive in environments that allow for creativity and personal expression. They excel in roles such as writers, artists, counselors, and entrepreneurs, where they can leverage their imagination and people skills. ENFPs are also natural leaders, capable of inspiring and motivating others toward shared goals. In relationships, ENFPs are warm, affectionate, and deeply invested in their partners. They seek meaningful connections and are willing to put in the effort to maintain and nurture their relationships. However, they can sometimes struggle with commitment and may need to work on balancing their desire for novelty with the stability of long-term partnerships. Overall, ENFPs are driven by a desire to explore, create, and connect. Their boundless energy, optimism, and ability to see the potential in others make them inspiring and influential individuals. They approach life with a sense of wonder and possibility, constantly seeking to make the world a more vibrant and meaningful place.
`;

const INFPdata = `
INFPs are idealistic, compassionate, and deeply committed to their personal values. They often have a rich inner life and a strong sense of purpose, driven by a desire to make the world a better place. Known for their empathy and ability to connect with others on a profound level, INFPs are highly attuned to the emotions and needs of those around them. They are creative and imaginative, often expressing themselves through art, writing, or other forms of personal expression. INFPs value authenticity and strive to live in alignment with their principles. While their idealism is a source of strength, it can also lead to challenges when reality doesn't meet their high expectations. INFPs may feel disillusioned or discouraged when their ideals clash with the practicalities of everyday life. They are prone to perfectionism and can be very hard on themselves, often setting impossibly high standards. Despite these challenges, INFPs are deeply dedicated to their causes and have a unique ability to inspire others. In their careers, INFPs excel in roles that allow for creativity and meaningful work. They often gravitate towards fields such as counseling, writing, art, and social work, where they can make a positive impact. Their empathetic nature makes them excellent listeners and supportive friends and colleagues. In relationships, INFPs seek deep, meaningful connections and are highly attuned to their partners' needs and feelings. They are supportive and nurturing, often going out of their way to ensure their loved ones feel valued and appreciated. However, they may struggle with expressing their own needs and setting boundaries. Overall, INFPs are driven by a desire to make a difference and live authentically. Their compassion, creativity, and dedication to their values make them influential and transformative individuals, capable of leaving a lasting impact on those they encounter.
`;

const ENTJdata = `
ENTJs are natural-born leaders, driven, ambitious, and strategic thinkers. They are often seen as the architects of their environments, always looking for ways to improve and optimize systems. ENTJs are highly confident and not afraid to take charge, making decisions that steer their teams and organizations toward success. They have a clear vision of what they want to achieve and are determined to reach their goals, often excelling in leadership and managerial roles. Known for their analytical skills and ability to solve complex problems, ENTJs thrive in situations that require strategic planning and critical thinking. They value efficiency and competence, often becoming impatient with inefficiency or incompetence. While their assertiveness and directness can sometimes come across as domineering or overly critical, their intentions are usually aimed at achieving the best possible outcomes. ENTJs are not easily swayed by emotions and prefer to make decisions based on logic and evidence. Despite their sometimes harsh exterior, they are deeply committed to their goals and the people they lead. In relationships, ENTJs seek partners who are equally ambitious and intellectually stimulating. They are supportive and loyal, often pushing their loved ones to reach their full potential. However, they may struggle with expressing their emotions and being sensitive to the emotional needs of others. In their careers, ENTJs excel in roles that allow them to take charge and implement their vision. They often find success in fields such as business, law, engineering, and politics, where their leadership and strategic skills can shine. Overall, ENTJs are driven by a desire to achieve excellence and make a significant impact. Their ambition, confidence, and strategic thinking make them powerful leaders capable of transforming their environments and achieving their goals.
`;

const INTJdata = `
INTJs are strategic and independent thinkers driven by a strong desire to understand and improve the world around them. Known for their analytical skills and ability to see patterns and connections that others might miss, INTJs are highly self-confident and often seen as visionaries. They prefer to work alone or in small, focused teams, valuing competence and efficiency. INTJs can be critical of those who do not meet their high standards and are not easily swayed by emotions, preferring to make decisions based on logic and evidence. While their independence and confidence can sometimes come across as aloof or detached, INTJs are deeply committed to their goals and to the people they care about. They are future-oriented and always looking for ways to improve systems and processes. In their careers, INTJs excel in roles that require strategic planning and problem-solving. They often find success in fields such as science, engineering, technology, and business, where their analytical skills and innovative thinking can shine. INTJs are not afraid to challenge the status quo and are often seen as agents of change, pushing for improvements and new ideas. In relationships, INTJs seek partners who are intellectually stimulating and share their drive for personal growth. They are loyal and supportive but may struggle with expressing their emotions and understanding the emotional needs of others. Overall, INTJs are driven by a desire to achieve their vision and make a significant impact. Their strategic thinking, independence, and determination make them influential and transformative individuals capable of driving progress and innovation. They approach life with a focus on continuous improvement and are always looking for ways to achieve their goals and make a difference.
`;

const ENTPdata = `
ENTPs are innovative, curious, and energetic individuals who are always looking for new challenges and opportunities. Known for their quick wit and ability to think on their feet, ENTPs enjoy debating and exploring new ideas. They are highly independent and value their freedom to think and act as they see fit, often challenging the status quo and pushing for change. ENTPs are natural problem solvers who thrive in environments that require creative thinking and adaptability. While their enthusiasm for new ideas can sometimes lead to difficulty in staying focused, their ability to see possibilities and connect disparate concepts makes them powerful innovators. ENTPs can sometimes be seen as argumentative or confrontational, but they usually enjoy the intellectual challenge rather than trying to prove others wrong. They are highly sociable and enjoy engaging with others, often bringing excitement and energy to any situation. In their careers, ENTPs excel in roles that allow for creativity and strategic thinking. They often find success in fields such as entrepreneurship, marketing, law, and technology, where their ability to generate and implement new ideas can shine. ENTPs are also natural leaders, capable of inspiring and motivating others toward shared goals. In relationships, ENTPs seek partners who are intellectually stimulating and share their enthusiasm for new experiences. They are supportive and encouraging but may struggle with commitment and consistency. Overall, ENTPs are driven by a desire to explore, innovate, and challenge conventions. Their creativity, adaptability, and ability to see the potential in new ideas make them inspiring and influential individuals. They approach life with a sense of adventure and possibility, constantly seeking to push boundaries and make a difference.
`;

const INTPdata = `
INTPs are analytical and independent thinkers driven by a strong desire to understand and explain the world around them. Known for their intellectual curiosity and ability to see patterns and connections that others might miss, INTPs value logic and evidence and prefer to make decisions based on reason rather than emotion. They are highly independent and prefer to work alone or in small, focused teams, often diving deeply into their areas of interest. INTPs can sometimes be seen as aloof or detached, but they are deeply committed to their ideas and theories. They enjoy exploring new concepts and possibilities, often becoming absorbed in their intellectual pursuits. While their independence and focus on logic can sometimes lead to challenges in understanding and expressing emotions, INTPs are loyal and supportive to those they care about. In their careers, INTPs excel in roles that require analytical thinking and problem-solving. They often find success in fields such as science, technology, engineering, and academia, where their ability to generate and analyze complex ideas can shine. INTPs are not afraid to challenge existing assumptions and are often seen as innovators, pushing for new and better ways of doing things. In relationships, INTPs seek partners who are intellectually stimulating and share their passion for learning. They may struggle with expressing their emotions and understanding the emotional needs of others, but they are deeply loyal and supportive. Overall, INTPs are driven by a desire to understand and innovate. Their analytical skills, intellectual curiosity, and independence make them powerful thinkers and innovators capable of making significant contributions to their fields. They approach life with a focus on discovery and understanding, constantly seeking to expand their knowledge and push the boundaries of what is possible.
`;

const ESFJdata = `
ESFJs are warm, caring, and sociable individuals who are deeply committed to their communities and the people they care about. Known for their ability to bring people together and create a sense of harmony, ESFJs are often seen as the caregivers and nurturers of their social circles. They value tradition and stability, preferring to maintain harmony and order in their environments. ESFJs are highly empathetic and have a unique ability to understand and connect with others, often going out of their way to make sure everyone feels valued and included. While their focus on others can sometimes lead to neglecting their own needs, their dedication and generosity make them invaluable members of their communities. ESFJs excel in roles that require interpersonal skills and a focus on helping others. They often find success in fields such as teaching, nursing, social work, and event planning, where their ability to organize and support others can shine. In their careers, ESFJs are reliable and hardworking, often going above and beyond to ensure that everything runs smoothly. They value recognition and appreciation for their efforts and are motivated by the positive impact they have on others. In relationships, ESFJs seek deep, meaningful connections and are highly attuned to their partners' needs and feelings. They are supportive, nurturing, and willing to invest significant effort into maintaining healthy, fulfilling relationships. However, they may struggle with expressing their own needs and setting boundaries, often prioritizing others' well-being over their own. Overall, ESFJs are driven by a desire to create harmony and support the people around them. Their warmth, empathy, and organizational skills make them influential and inspiring individuals who are capable of making a significant positive impact on their communities. They approach life with a focus on relationships and connection, constantly seeking to bring people together and make the world a better place.
`;

const ISFJdata = `
ISFJs are loyal, practical, and compassionate individuals who are deeply committed to their responsibilities and the people they care about. Known for their reliability and strong sense of duty, ISFJs are often seen as the backbone of their communities. They value tradition and stability, preferring to maintain order and harmony in their environments. ISFJs are highly empathetic and have a unique ability to understand and connect with others, often going out of their way to make sure everyone feels valued and included. While their focus on others can sometimes lead to neglecting their own needs, their dedication and compassion make them invaluable members of their communities. ISFJs excel in roles that require attention to detail and a focus on helping others. They often find success in fields such as healthcare, education, social work, and administrative support, where their reliability and organizational skills can shine. In their careers, ISFJs are dependable and hardworking, often going above and beyond to ensure that everything runs smoothly. They value recognition and appreciation for their efforts and are motivated by the positive impact they have on others. In relationships, ISFJs seek deep, meaningful connections and are highly attuned to their partners' needs and feelings. They are supportive, nurturing, and willing to invest significant effort into maintaining healthy, fulfilling relationships. However, they may struggle with expressing their own needs and setting boundaries, often prioritizing others' well-being over their own. Overall, ISFJs are driven by a desire to create harmony and support the people around them. Their loyalty, practicality, and empathy make them influential and inspiring individuals who are capable of making a significant positive impact on their communities. They approach life with a focus on relationships and connection, constantly seeking to bring people together and make the world a better place.
`;

const ESTJdata = `
ESTJs are organized, practical, and assertive individuals driven by a strong sense of duty and responsibility. Known for their leadership skills and ability to bring order and stability to their environments, ESTJs are often seen as the leaders and organizers of their communities. They value tradition and prefer to maintain established systems and procedures, often excelling in roles that require structure and discipline. ESTJs are highly confident and not afraid to take charge, making decisions that steer their teams and organizations toward success. While their assertiveness and directness can sometimes come across as domineering or overly critical, their intentions are usually aimed at achieving the best possible outcomes. ESTJs value efficiency and competence, often becoming impatient with inefficiency or incompetence. Despite their sometimes harsh exterior, they are deeply committed to their responsibilities and the people they lead. In their careers, ESTJs excel in roles that require strong organizational and leadership skills. They often find success in fields such as business, management, law enforcement, and the military, where their ability to create order and achieve results can shine. ESTJs are not afraid to challenge the status quo and are often seen as agents of change, pushing for improvements and new ideas. In relationships, ESTJs seek partners who are equally driven and supportive of their goals. They are loyal and dependable but may struggle with expressing their emotions and understanding the emotional needs of others. Overall, ESTJs are driven by a desire to achieve excellence and make a significant impact. Their ambition, confidence, and strategic thinking make them powerful leaders capable of transforming their environments and achieving their goals. They approach life with a focus on continuous improvement and are always looking for ways to achieve their goals and make a difference.
`;

const ISTJdata = `
ISTJs are practical, reliable, and responsible individuals driven by a strong sense of duty and commitment. Known for their attention to detail and ability to follow through on their commitments, ISTJs are often seen as the backbone of their communities. They value tradition and stability, preferring to maintain order and structure in their environments. ISTJs are highly dependable and are often seen as the backbone of their communities. While their focus on tradition and structure can sometimes come across as rigid or inflexible, their intentions are usually aimed at achieving the best possible outcomes. ISTJs value competence and efficiency, often becoming impatient with inefficiency or incompetence. Despite their sometimes reserved exterior, they are deeply committed to their responsibilities and the people they care about. In their careers, ISTJs excel in roles that require attention to detail and a focus on practicality and reliability. They often find success in fields such as accounting, law, engineering, and administration, where their ability to create order and achieve results can shine. ISTJs are not afraid to challenge the status quo and are often seen as agents of change, pushing for improvements and new ideas. In relationships, ISTJs seek partners who are equally dependable and supportive of their goals. They are loyal and dependable but may struggle with expressing their emotions and understanding the emotional needs of others. Overall, ISTJs are driven by a desire to achieve excellence and make a significant impact. Their reliability, attention to detail, and commitment to their responsibilities make them powerful leaders capable of transforming their environments and achieving their goals. They approach life with a focus on continuous improvement and are always looking for ways to achieve their goals and make a difference.
`;

const ESFPdata = `
ESFPs are enthusiastic, outgoing, and spontaneous individuals who bring energy and excitement to any situation. Known for their ability to live in the moment and make the most of every experience, ESFPs are often seen as the life of the party. They are highly sociable and enjoy connecting with others, often bringing joy and positivity to those around them. ESFPs are highly empathetic and have a unique ability to understand and connect with others, often going out of their way to make sure everyone feels valued and included. While their focus on living in the moment can sometimes lead to difficulty in planning for the future, their enthusiasm and ability to adapt make them powerful influencers. ESFPs can sometimes be seen as impulsive or attention-seeking, but they usually enjoy the social interaction rather than trying to prove others wrong. They are highly sociable and enjoy engaging with others, often bringing excitement and energy to any situation. In their careers, ESFPs excel in roles that allow for creativity and personal expression. They often find success in fields such as entertainment, hospitality, healthcare, and sales, where their ability to connect with others can shine. ESFPs are also natural leaders, capable of inspiring and motivating others toward shared goals. In relationships, ESFPs seek partners who are equally outgoing and supportive of their goals. They are supportive and loyal, often pushing their loved ones to reach their full potential. However, they may struggle with commitment and consistency. Overall, ESFPs are driven by a desire to explore, innovate, and connect. Their creativity, adaptability, and ability to see the potential in new ideas make them inspiring and influential individuals. They approach life with a sense of adventure and possibility, constantly seeking to push boundaries and make a difference.
`;

const ISFPdata = `
ISFPs are gentle, compassionate, and creative individuals who are deeply in tune with their surroundings and the people around them. Known for their artistic talents and ability to express themselves through various forms of art, ISFPs often have a unique sense of style and a keen eye for beauty. They value individuality and authenticity, seeking to live in alignment with their personal values. ISFPs are highly empathetic and have a unique ability to understand and connect with others, often going out of their way to make sure everyone feels valued and included. While their focus on personal expression can sometimes lead to difficulty in dealing with criticism, their sensitivity and ability to adapt make them powerful influencers. ISFPs can sometimes be seen as reserved or shy, but they usually enjoy the social interaction rather than trying to prove others wrong. They are highly sociable and enjoy engaging with others, often bringing excitement and energy to any situation. In their careers, ISFPs excel in roles that allow for creativity and personal expression. They often find success in fields such as art, music, healthcare, and education, where their ability to connect with others can shine. ISFPs are also natural leaders, capable of inspiring and motivating others toward shared goals. In relationships, ISFPs seek partners who are equally gentle and supportive of their goals. They are supportive and loyal, often pushing their loved ones to reach their full potential. However, they may struggle with commitment and consistency. Overall, ISFPs are driven by a desire to explore, innovate, and connect. Their creativity, adaptability, and ability to see the potential in new ideas make them inspiring and influential individuals. They approach life with a sense of adventure and possibility, constantly seeking to push boundaries and make a difference.
`;

const ESTPdata = `
ESTPs are energetic, outgoing, and action-oriented individuals who thrive in fast-paced environments. Known for their quick thinking and ability to make decisions on the fly, ESTPs are natural problem solvers who enjoy tackling challenges head-on. They are highly sociable and enjoy being the center of attention, often bringing excitement and energy to any situation. ESTPs value freedom and spontaneity and prefer to live in the moment, often becoming easily bored with routine or repetitive tasks. While their focus on the present can sometimes lead to difficulty in planning for the future, their charisma and confidence make them effective and dynamic leaders. ESTPs can sometimes be seen as impulsive or reckless, but they usually enjoy the excitement and challenges rather than trying to prove others wrong. They are highly sociable and enjoy engaging with others, often bringing excitement and energy to any situation. In their careers, ESTPs excel in roles that allow for quick thinking and action. They often find success in fields such as sales, marketing, entrepreneurship, and emergency services, where their ability to make quick decisions and solve problems can shine. ESTPs are also natural leaders, capable of inspiring and motivating others toward shared goals. In relationships, ESTPs seek partners who are equally outgoing and supportive of their goals. They are supportive and loyal, often pushing their loved ones to reach their full potential. However, they may struggle with commitment and consistency. Overall, ESTPs are driven by a desire to explore, innovate, and connect. Their creativity, adaptability, and ability to see the potential in new ideas make them inspiring and influential individuals. They approach life with a sense of adventure and possibility, constantly seeking to push boundaries and make a difference.
`;

const ISTPdata = `
ISTPs are practical, analytical, and resourceful individuals who are driven by a strong desire to understand how things work. Known for their mechanical skills and ability to troubleshoot and solve complex problems, ISTPs are highly independent and prefer to work alone or in small, focused teams. They value efficiency and prefer to make decisions based on logic and evidence, often becoming impatient with inefficiency or incompetence. While their independence and focus on logic can sometimes lead to challenges in understanding and expressing emotions, ISTPs are deeply committed to their work and to the people they care about. They enjoy exploring new ideas and possibilities and are often seen as the innovators of their environments. In their careers, ISTPs excel in roles that require practical thinking and problem-solving skills. They often find success in fields such as engineering, mechanics, technology, and skilled trades, where their ability to troubleshoot and solve problems can shine. ISTPs are not afraid to challenge existing assumptions and are often seen as innovators, pushing for new and better ways of doing things. In relationships, ISTPs seek partners who are equally independent and supportive of their goals. They are loyal and dependable but may struggle with expressing their emotions and understanding the emotional needs of others. Overall, ISTPs are driven by a desire to achieve excellence and make a significant impact. Their analytical skills, practical thinking, and independence make them powerful thinkers and innovators capable of making significant contributions to their fields. They approach life with a focus on discovery and understanding, constantly seeking to expand their knowledge and push the boundaries of what is possible.
`;
export {
    ENFJdata,ENFPdata,ENTJdata,ENTPdata,ESFJdata,ESFPdata,ESTJdata,ESTPdata,INFJdata,INFPdata,INTJdata,INTPdata,ISFJdata,ISFPdata,ISTJdata,ISTPdata
}